# Generated by Django 4.2.1 on 2024-08-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cost', models.FloatField(verbose_name='Цена')),
                ('sale', models.FloatField(default=0, verbose_name='Скидка в процентах')),
                ('image', models.ImageField(upload_to='photos/')),
                ('stars', models.IntegerField(verbose_name='Оценка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.category')),
            ],
        ),
    ]
