# Generated by Django 5.1 on 2024-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Контент')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('image', models.ImageField(blank=True, upload_to='blogs/')),
            ],
        ),
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Контент')),
                ('button_name', models.CharField(max_length=50, verbose_name='Заголовок кнопки перехода')),
                ('image', models.ImageField(blank=True, upload_to='slides/')),
            ],
        ),
    ]
