# Generated by Django 5.1 on 2024-08-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_blog_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название  категории')),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
