# Generated by Django 5.1 on 2024-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_blog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
