# Generated by Django 5.1 on 2024-08-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_product_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.DeleteModel(
            name='blog_categories',
        ),
    ]
