# Generated by Django 5.1 on 2024-08-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('index', models.TextField(null=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='description', to='menu.product')),
            ],
        ),
    ]
