# Generated by Django 5.1 on 2024-08-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_product_keywords_productdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='keywords',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='description',
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='fid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='index',
            field=models.JSONField(null=True),
        ),
    ]
